name: update-readme

on:
  schedule:
    - cron:  '15 13 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.2
      - run: |
          pip install requests
          git config user.name ZJUGuoShuai
          git config user.email gs0801@foxmail.com
          python run.py --run-in-gh
          git add .
          git commit -m "update statistics from GitHub Actions"
          git push
